[ptp_domain 0]
interfaces enp3s0f0

[timemaster]
ntp_program chronyd

[chrony.conf]
include /etc/chrony.conf

[ptp4l.conf]
unicast_req_duration    60
slaveOnly               1
network_transport       UDPv6

>[enp3s0f0]
unicast_master_table    1

>[unicast_master_table]
table_id                1
logQueryInterval        2
UDPv6                   2620:118:5008:10f8:4498:1000:319:B

[chronyd]
path /usr/sbin/chronyd

[phc2sys]
path /usr/sbin/phc2sys

[ptp4l]
path /usr/sbin/ptp4l
